experiment_name: 'resnet18-imagenet-a3w3'

model:
  class_name: 'model.resnet.resnet18'
  params:
    pretrained: true

checkpoint:
  path:

dataset:
  name: imagenet
  data_dir: '/home/hzzhu/Dataset/imagenet'
  batch_size: 64
  workers: 16

trainer:
  gpus: [ 0,1,2,3 ]
  max_epochs: 90

quan:
  act: # (default for activations of all quantized modules)
    class_name: 'LSQQuantizer'
    params:
      bit: 3
      all_positive: true
  weight: # (default for weights all modules)
    class_name: 'LSQQuantizer'
    params:
      bit: 3
  excepts:
    conv1:
      act:
        class_name:
        params:
          bit: 8
          all_positive: false
      weight:
        class_name:
        params:
          bit: 8
    fc:
      act:
        class_name:
        params:
          bit: 8
      weight:
        class_name:
        params:
          bit: 8

optimizer:
  class_name: 'SGD'
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  class_name: 'StepLR'
  params:
    step_size: 30
    gamma: 0.1
