experiment_name: 'resnet18-imagenet-a3w3-lsq'

model:
  class_name: 'resnet18'
  params:
    pretrained: true

checkpoint:
  path:

trainer:
  gpus: [ 0, 1, 2, 3, 4 ]
  max_epochs: 90
  # precision: 16
  num_sanity_val_steps: 0

dataset:
  name: imagenet
  data_dir: '/home/hzzhu/Dataset/imagenet'
  batch_size: 128
  workers: 10

quan:
  act: # (default for activations of all quantized modules)
    class_name: 'LearnedStepQuantizer'
    params:
      bit: 3
      all_positive: true
  weight: # (default for weights all modules)
    class_name: 'LearnedStepQuantizer'
    params:
      bit: 3
  excepts:
    conv1:
      act:
        params:
          bit: 8
          all_positive: false
      weight:
        params:
          bit: 8
    fc:
      act:
        params:
          bit: 8
      weight:
        params:
          bit: 8

optimizer:
  class_name: 'SGD'
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  class_name: 'StepLR'
  params:
    step_size: 30
    gamma: 0.1
