experiment_name: 'resnet50-imagenet-a6w6v64-vsquant'

model:
  class_name: 'resnet50'
  params:
    pretrained: true

checkpoint:
  path:

trainer:
  devices: [ 0, 1, 2, 3, 4 ]
  max_epochs: 90
  # precision: 16
  num_sanity_val_steps: 0

dataset:
  name: imagenet
  data_dir: '/home/hzzhu/Dataset/imagenet'
  num_classes: 1000
  batch_size: 128
  workers: 10

quan:
  act: # (default for activations of all quantized modules)
    class_name: 'PerVectorScaledQuantizer'
    params:
      bit: 6
      all_positive: true
      vector_len: 64
      scale_bit: -1
  weight: # (default for weights all modules)
    class_name: 'PerVectorScaledQuantizer'
    params:
      bit: 6
      all_positive: true
      vector_len: 64
      scale_bit: -1
  excepts:


optimizer:
  class_name: 'SGD'
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  class_name: 'CosineAnnealingLR'
  params:
    T_max: 90
